### ISSUE TITLE
about downsampled

### ISSUE THREAD

**Issue by BridgetteSong** [LEEYOONHYUNG/BVAE-TTS#10]
I found a problem about downsampled in the time dimension of mel-spectrograms.

1. in the training, mel-spectrogram is downsampled, so dimension of the attention map along mel-spectrograms time dimension will be scaled(1/4 * T_mel in the code). So all the durations will expand average 4 times in the inferencing. Avoiding to not skip words, the duration has a min value 1, which means all durations will has at least 4 times duration.
2. 1 will cause slower speed than original speed and unreasonable durations, and can't also keep global monotonous attention map.
3. I want to know what happens if  I do not use time dimension downsampled and only keep feature hidden dimension downsampled. egs. Learning attention is hard? or training is difficult? This can improve quality?

**Comment by LEEYOONHYUNG** [comment]
Thank you for your attention to our work.
The reason we downsampled the time dimension is that learning attention gets easier in that case, and it was really important for this work to learn stable attention through the whole training process.

For question 1, we conjecture that it can rather give more room for the decoder to use the phonemes, but we do not conduct a deep analysis about it.
