### ISSUE TITLE
Share the bottom-up and top-down parameters

### ISSUE THREAD

**Issue by wizardk** [LEEYOONHYUNG/BVAE-TTS#11]
In your paper, it's said "the variational inference is designed in a bidirectional way based on bottom-up path and top-down path, while letting the inference network (left) and generative network (right) **share** their parameters as shown in Figure 1."
But in your code, I didn't find a place to share parameters. Can you tell me what I missed?
Thank you in advance.

**Comment by LEEYOONHYUNG** [comment]
It means that NN modules belonging to the top-down path are used as a part of both the encoder (variational inference) and the decoder (generative network) of the BVAE.
