### ISSUE TITLE
Why do you use MAE as the loss function for recog?

### ISSUE THREAD

**Issue by wizardk** [LEEYOONHYUNG/BVAE-TTS#12]
For the effect, is there any big difference between MAE or MSE for recog?

**Comment by LEEYOONHYUNG** [comment]
Thank you for your attention. I'm sorry but I did not compare the MAE and MSE losses. 😅
As far as I know, MAE loss is more robust to the outliers but I think it would be better to use each loss and compare them.

**Comment by wizardk** [comment]
@LEEYOONHYUNG Hi, one more question. Why did you use min & max normalization with sigmoid? Have you tried to use mean and std normalization without sigmoid?

**Comment by LEEYOONHYUNG** [comment]
Sorry for the late response. I used min & max normalization because it stabilizes the training. However, unfortunately, I did not try mean and std normalization.
