### ISSUE TITLE
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0     Excuse me，what is the reason for this problem?

### ISSUE THREAD

**Issue by CrazyCharles6** [LEEYOONHYUNG/BVAE-TTS#3]

**Comment by LEEYOONHYUNG** [comment]
It is a function in the apex that adjusts the loss scale to prevent the gradient signal from disappearing.

**Comment by CrazyCharles6** [comment]
So this is not a problem with the program, but just a hint? The program hasn't responded for a long time, I think there is a problem with the program. Thank you very much for your answer.

**Comment by CookiePPP** [comment]
> Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 32768.0

a loss scale of 32768 does not indicate any sort of failure or issue.

If there is another problem then it would be useful to post a screenshot or a copy/paste of the outputs so it's easier to see what's going on.
