### ISSUE TITLE
학습 관련 질문이 있습니다

### ISSUE THREAD

**Issue by easy-hyun** [LEEYOONHYUNG/BVAE-TTS#8]
안녕하세요. 
Bidirectional VAE 부분을 다른 모델에 적용해서 학습시켜 보고 있습니다.
그런데 학습 과정에서 kl-loss 부분이 nan이 되는 경우가 자주 발생하는데
VAE 부분에서 학습이 안정화되지 않는 현상이 발생하는 것 같습니다.
혹시 학습이 잘 안 되는 경우가 존재했었나요?
그리고 이러한 경우에는 어떻게 해결하셨는지 도움을 얻고자 issue 남겨드립니다.
감사합니다!

**Comment by LEEYOONHYUNG** [comment]
안녕하세요. 네, 저도 모델이 학습에 실패하는 경우를 종종 경험했었고, 그래서 exp 대신 softplus를 쓴다거나 sqrt(2)로 나눠주는 등의 방법을 사용했었는데요. 현재로서는 제가 상황을 알 수 없어 exp나 log가 포함되는 코드들을 먼저 살펴보시면 좋을 것 같다고 밖에 말씀을 드릴 수 없을 것 같습니다 ㅠㅠ

**Comment by easy-hyun** [comment]
좋은 답변해 주셔서 감사합니다ㅎㅎ 좀 더 찾아보면서 확인해 보도록 하겠습니다!! 감사합니다!!
