### ISSUE TITLE
How to select the best model?

### ISSUE THREAD

**Issue by wizardk** [LEEYOONHYUNG/BVAE-TTS#9]
Hi, thanks for your good research. Is it determined by observing the val_recon_loss to select the best model?

**Comment by LEEYOONHYUNG** [comment]
Since we found out that it was difficult to choose a model based on loss curves, we manually listened to the audio samples.

**Comment by wizardk** [comment]
@LEEYOONHYUNG Hi, I have another question. Why does align_loss rise and duration_loss fall in training?
![loss](https://user-images.githubusercontent.com/20595052/144809451-766e25aa-15e9-4a9f-8423-9c15d7db1b7f.png)
